language: ruby
sudo: false
install:
  - bundle install --jobs=3 --retry=3
cache: bundler
services:
  - postgresql
addons:
  postgresql: '9.4'
env:
  - RAILS_ENV=test
script:
  - bundle exec rubocop --config .rubocop.yml
  - bundle exec rspec spec
